## Basic Configuration
baseurl = "https://nirantk.com/"
languageCode = "en"

title = "Nirant Kasliwal"
theme = "ananke"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  background_color_class = "bg-black"
  favicon=""
  linkedin="https://www.linkedin.com/in/nirant"
  twitter = "https://twitter.com/@NirantK"
  github="https://github.com/NirantK"
  recent_posts_number = 5

pygmentsUseClassic=true
pygmentsUseClasses=true
relatedPosts = true
postNavigation = true

[[menu.main]]
name = "about"
identifier = "about"
url = "/about"

[[menu.main]]
name = "newsletter"
identifier = "newsletter"
url = "https://niranting.substack.com/"

[[menu.main]]
name = "now"
identifier = "now"
url = "/now"

[[menu.main]]
name = "writing"
identifier = "writing"
url = "/writing"

[[menu.main]]
name = "home"
identifier = "home"
url = "/"
